function report = matlab_dash_calibration(output_dir)
%MATLAB_DASH_CALIBRATION 最小水平虚线校准；不运行论文数值实验或重绘旧图。
% 只新建一条 RGB=[.70 .10 .12]、LineWidth=.9 pt、LineStyle='--' 的水平线。
% 原 Renderer/RendererMode 由当前 MATLAB 环境继承，不设置为 painters。
% 原生 PNG(on/off) 与独立 vector/print/SVG 候选使用同一新 HG 场景的干净副本。
% 两次独立进程应使用不同空 output_dir；结果不能用作预设 dash 长度的证明。
output_dir = char(output_dir);
if ~isfolder(output_dir), mkdir(output_dir); end
summary_file = fullfile(output_dir, 'dash_calibration.json');
assert(~isfile(summary_file), 'Refusing to overwrite an existing calibration.');
assert(exist('matlab_heatmap_image_candidate', 'file') == 2 && ...
    exist('matlab_export_candidate', 'file') == 2, 'Candidate helpers must be on the MATLAB path.');

target_size_bp = [451.28 140];
fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'points', ...
    'Position', [64 64 target_size_bp]);
figure_guard = onCleanup(@() close_if_valid(fig)); %#ok<NASGU>
ax = axes(fig, 'Units', 'points', 'Position', [25.5 45 400.5 70.5]);
hold(ax, 'on');
h = plot(ax, [0 1], [.5 .5], '--', 'Color', [.70 .10 .12], ...
    'LineWidth', .9, 'Marker', 'none');
ax.XLim = [0 1]; ax.YLim = [0 1];
ax.XTick = []; ax.YTick = []; ax.Box = 'off'; ax.Visible = 'off';
if isprop(ax, 'Toolbar') && ~isempty(ax.Toolbar), ax.Toolbar.Visible = 'off'; end
drawnow;
source = struct('renderer', char(fig.Renderer), 'renderer_mode', char(fig.RendererMode), ...
    'graphics_smoothing', char(fig.GraphicsSmoothing), ...
    'screen_pixels_per_inch', double(get(groot, 'ScreenPixelsPerInch')), ...
    'line_color', h.Color, 'line_width_bp', h.LineWidth, 'line_style', h.LineStyle, ...
    'XData', h.XData, 'YData', h.YData, 'target_size_bp', target_size_bp, ...
    'axes_position_bp', ax.Position, 'axes_visible', char(ax.Visible));

native = matlab_heatmap_image_candidate(fig, ...
    fullfile(output_dir, 'dash_horizontal_source_renderer'), target_size_bp);
vector = matlab_export_candidate(fig, ...
    fullfile(output_dir, 'dash_horizontal_vector_modes'), target_size_bp);
report = struct('purpose', 'minimal horizontal dash physical-length calibration', ...
    'status', 'experiment_completed', 'matlab_version', version, 'source', source, ...
    'native_image', native, 'native_vector_modes', vector, ...
    'all_exports_succeeded', native.all_exports_succeeded && vector.all_exports_succeeded, ...
    'measurement_required', true, ...
    'measurement_method', ['At PNG600, select red pixels and measure complete interior ' ...
        'horizontal runs and gaps; omit the two clipped end runs. Convert using the ' ...
        'reported full export width and actual PNG width, then compare the vector ' ...
        'PDF dash array. Do not assume either dash ratio in advance.'], ...
    'historical_content_used', false, 'full_manuscript_recomputation_performed', false);
fid = fopen(summary_file, 'w', 'n', 'UTF-8');
assert(fid >= 0, 'Cannot open the dash calibration report.');
file_guard = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', jsonencode(report));
fprintf('MATLAB_DASH_CALIBRATION_COMPLETE %s\n', summary_file);
end

function close_if_valid(fig)
if ~isempty(fig) && isgraphics(fig, 'figure'), delete(fig); end
end
